version: "2"
services:
  subscription-bff:
    container_name: adidas-email-server-mcsv
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: adidas-email-server-mcsv:latest
    ports:
      - "8082:8082"
    environment:
      - TZ=America/Sao_Paulo
